---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-2
provisioner: docker.io/hostpath
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume-2
  labels:
    type: local
spec:
  storageClassName: local-storage-2
  claimRef:
    name: jenkins-pv-claim
    namespace: devops-tools
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/d/jenkins
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim-2
  namespace: devops-tools
spec:
  storageClassName: local-storage-2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi